export type Locale = 'es' | 'ru';

export const ui = {
  es: {
    nav: ['Método', 'Clases', 'Horarios', 'Sobre mí', 'Blog'], reserve: 'Reservar', openMenu: 'Abrir menú', closeMenu: 'Cerrar menú', mainNav: 'Navegación principal', homeLabel: 'Yoga Funcional Panamá, inicio', skip: 'Saltar al contenido', socials: 'Redes sociales',
    meta: { title: 'Yoga Funcional en Panamá | Iosif Ruiz', description: 'Yoga Funcional en Panamá con Iosif Ruiz. Entrenamiento de fuerza, movilidad, equilibrio, coordinación, respiración y atención.' },
    hero: { kicker: 'ENTRENAMIENTO / ATENCIÓN / RECUPERACIÓN', alt: 'Persona practicando yoga funcional sobre una esterilla rosa', quote: 'No entrenamos a la persona para hacer yoga.', strong: 'Usamos el yoga para entrenar a la persona.', soon: 'CLASES / PRÓXIMAMENTE' },
    method: { number: '02 / MÉTODO', title: ['Del cuerpo', 'hacia la', 'postura'], copy: 'Yoga Funcional es un método de entrenamiento que utiliza herramientas del yoga para desarrollar fuerza, movilidad, equilibrio, coordinación, respiración, atención y recuperación.', copy2: 'No adaptamos el cuerpo a una asana.', copy3: 'Elegimos la postura según lo que el cuerpo necesita trabajar.', label: 'Capacidades que entrenamos', concepts: ['Fuerza','Movilidad','Equilibrio','Coordinación','Respiración','Atención','Recuperación'], descriptions: ['No buscamos fuerza por la fuerza. La usamos para crear estabilidad, control y capacidad de movimiento.','No se trata de llegar más lejos. Entrenamos el movimiento que tu cuerpo puede controlar y utilizar.','No es quedarse quieto sin caer. Es aprender a responder cuando cambia tu posición, el apoyo o el movimiento.','Entrenamos al cuerpo para organizar movimientos diferentes como una sola acción: con precisión, ritmo y control.','No respiramos de una forma porque sea «correcta». Usamos la respiración según lo que estamos haciendo y el estado que necesitamos.','Entrenamos la capacidad de dirigir y mantener la atención sobre el cuerpo, la respiración y lo que estamos haciendo ahora.','No todo es activación y esfuerzo. También entrenamos la capacidad de bajar la activación y facilitar la recuperación.'], end: 'CUERPO ≠ FORMA   /   CUERPO = INFORMACIÓN' },
    classes: { number:'03 / CLASES', title:['Entrena','A tu manera'], formats:[['Clase general','Entrena en grupo siguiendo la estructura de Yoga Funcional, con opciones adaptadas a diferentes niveles. No necesitas experiencia previa para empezar.','Horarios, ubicación y condiciones dependen del espacio donde se realiza la clase.','Ver horarios'],['Clase individual','Una sesión uno a uno adaptada a tu nivel, tus necesidades y lo que quieres trabajar.','Sin programas ni compromisos: una clase, un objetivo, una hora de trabajo.','Reservar'],['Entrenamiento personal','Un proceso diseñado alrededor de ti: evaluación, objetivos, programa de entrenamiento, progresión y ajustes.','No es solamente una clase. Es un plan para trabajar hacia un resultado concreto.','Reservar']] },
    schedule:{number:'04 / HORARIOS',title:['Horario','De grupo'],info:'Información de las clases',kind:'Clase general',days:['Martes','Jueves','Sábado'],label:'Horario actual en Clayton'},
    about:{number:'05 / SOBRE MÍ',alt:'Iosif Ruiz sentado en postura de loto',intro:'Profesor de yoga y meditación.',paragraphs:['Llevo más de 20 años practicando yoga y meditación y enseño desde 2010. Pero mi experiencia nunca se limitó solamente al yoga.','A lo largo de estos años he explorado diferentes escuelas de yoga y meditación, tradiciones budistas, artes marciales y distintas formas de entrenamiento físico. Cada una me dio herramientas y una manera diferente de entender el movimiento, el esfuerzo, la respiración, la atención y la recuperación.','De ese recorrido nació Yoga Funcional. No como una nueva tradición ni como una colección de ejercicios, sino como un método propio que integra esas herramientas en una práctica completa: fuerza, movilidad, equilibrio, coordinación, respiración, atención, activación y recuperación.','No necesitas compartir una filosofía determinada para practicar conmigo.'],statement:['Que todo lo que hacemos durante una práctica','tenga una utilidad fuera de ella.']},
    contact:{number:'06 / CONTACTO',title:'¿ENTRE\u00adNAMOS?',closing:['PUEDES SEGUIR BUSCANDO.','O PUEDES EMPEZAR A ENTRENAR.']},
    blog:{title:'Blog | Yoga Funcional Panamá',description:'Artículos sobre Yoga Funcional, fuerza, movilidad, respiración, atención, recuperación y meditación.',taxonomy:'YOGA · MOVIMIENTO · MEDITACIÓN · CUERPO · ATENCIÓN',read:'LEER ARTÍCULO',readLabel:'Leer artículo',empty:'Todavía no hay artículos publicados.',back:'← BLOG',edit:'EDITAR ↗',by:'POR',updated:'ACTUALIZADO',previous:'← ANTERIOR',next:'SIGUIENTE →',all:'VER TODOS LOS ARTÍCULOS',articleNav:'Navegación entre artículos',share:'COMPARTIR ↗',copied:'ENLACE COPIADO ✓',copiedStatus:'El enlace del artículo se copió al portapapeles.',shareError:'No se pudo abrir el menú para compartir.',copyPrompt:'Copia el enlace de este artículo:',copyStatus:'Selecciona y copia el enlace mostrado.'}
  },
  ru: {
    nav: ['Метод', 'Занятия', 'Расписание', 'Обо мне', 'Блог'], reserve: 'Записаться', openMenu: 'Открыть меню', closeMenu: 'Закрыть меню', mainNav: 'Основная навигация', homeLabel: 'Yoga Funcional Panamá, главная', skip: 'Перейти к содержанию', socials: 'Социальные сети',
    meta:{title:'Функциональная йога в Панаме | Иосиф Руис',description:'Функциональная йога в Панаме с Иосифом Руисом. Тренировка силы, мобильности, равновесия, координации, дыхания и внимания.'},
    hero:{kicker:'ТРЕНИРОВКА / ВНИМАНИЕ / ВОССТАНОВЛЕНИЕ',alt:'Человек практикует функциональную йогу на розовом коврике',quote:'Мы не тренируем человека, чтобы он занимался йогой.',strong:'Мы используем йогу, чтобы тренировать человека.',soon:'ЗАНЯТИЯ / СКОРО'},
    method:{number:'02 / МЕТОД',title:['От тела','к','позе'],copy:'Функциональная йога — метод тренировки, использующий инструменты йоги для развития силы, мобильности, равновесия, координации, дыхания, внимания и восстановления.',copy2:'Мы не приспосабливаем тело к асане.',copy3:'Мы выбираем позу в соответствии с тем, над чем нужно работать телу.',label:'Развиваемые качества',concepts:['Сила','Мобильность','Равновесие','Координация','Дыхание','Внимание','Восстановление'],descriptions:['Мы не стремимся к силе ради силы. Мы используем её для развития устойчивости, контроля и способности двигаться.','Цель не в том, чтобы продвинуться дальше. Мы тренируем движение, которое тело способно контролировать и использовать.','Это не просто неподвижность без падения. Мы учимся реагировать на изменение положения, опоры или движения.','Мы тренируем тело объединять разные движения в одно действие — точное, ритмичное и контролируемое.','Мы не дышим определённым образом только потому, что он считается «правильным». Мы используем дыхание в соответствии с действием и нужным состоянием.','Мы тренируем способность направлять и удерживать внимание на теле, дыхании и текущем действии.','Не всё сводится к активности и усилию. Мы также тренируем способность снижать активность и способствовать восстановлению.'],end:'ТЕЛО ≠ ФОРМА   /   ТЕЛО = ИНФОРМАЦИЯ'},
    classes:{number:'03 / ЗАНЯТИЯ',title:['Тренируйся','По-своему'],formats:[['Общее занятие','Тренируйтесь в группе по структуре функциональной йоги с вариантами для разных уровней. Предварительный опыт не нужен.','Расписание, место и условия зависят от площадки проведения занятия.','Расписание'],['Индивидуальное занятие','Индивидуальная сессия, адаптированная к вашему уровню, потребностям и целям.','Без программ и обязательств: одно занятие, одна цель, один час работы.','Записаться'],['Персональная тренировка','Процесс, построенный вокруг вас: оценка, цели, программа тренировок, прогресс и корректировки.','Это не просто занятие. Это план работы для достижения конкретного результата.','Записаться']]},
    schedule:{number:'04 / РАСПИСАНИЕ',title:['Групповые','Тренировки'],info:'Информация о занятиях',kind:'Общее занятие',days:['Вторник','Четверг','Суббота'],label:'Текущее расписание в Clayton'},
    about:{number:'05 / ОБО МНЕ',alt:'Иосиф Руис сидит в позе лотоса',intro:'Преподаватель йоги и медитации.',paragraphs:['Я практикую йогу и медитацию более 20 лет и преподаю с 2010 года. Но мой опыт никогда не ограничивался только йогой.','За эти годы я изучал разные школы йоги и медитации, буддийские традиции, боевые искусства и различные формы физической подготовки. Каждая из них дала мне инструменты и иной взгляд на движение, усилие, дыхание, внимание и восстановление.','Из этого пути родилась функциональная йога. Не как новая традиция или набор упражнений, а как собственный метод, объединяющий эти инструменты в целостную практику: силу, мобильность, равновесие, координацию, дыхание, внимание, активацию и восстановление.','Чтобы заниматься со мной, не нужно разделять определённую философию.'],statement:['Пусть всё, что мы делаем во время практики,','приносит пользу за её пределами.']},
    contact:{number:'06 / КОНТАКТ',title:'ТРЕНИРУЕМСЯ?',closing:['МОЖНО ПРОДОЛЖАТЬ ИСКАТЬ.','А МОЖНО НАЧАТЬ ТРЕНИРОВАТЬСЯ.']},
    blog:{title:'Блог | Yoga Funcional Panamá',description:'Статьи о функциональной йоге, силе, мобильности, дыхании, внимании, восстановлении и медитации.',taxonomy:'ЙОГА · ДВИЖЕНИЕ · МЕДИТАЦИЯ · ТЕЛО · ВНИМАНИЕ',read:'ЧИТАТЬ СТАТЬЮ',readLabel:'Читать статью',empty:'Пока нет опубликованных статей.',back:'← БЛОГ',edit:'РЕДАКТИРОВАТЬ ↗',by:'АВТОР',updated:'ОБНОВЛЕНО',previous:'← ПРЕДЫДУЩАЯ',next:'СЛЕДУЮЩАЯ →',all:'ВСЕ СТАТЬИ',articleNav:'Навигация по статьям',share:'ПОДЕЛИТЬСЯ ↗',copied:'ССЫЛКА СКОПИРОВАНА ✓',copiedStatus:'Ссылка на статью скопирована.',shareError:'Не удалось открыть меню «Поделиться».',copyPrompt:'Скопируйте ссылку на статью:',copyStatus:'Выделите и скопируйте показанную ссылку.'}
  }
} as const;

export const localizedPath = (locale: Locale, path = '') => `${import.meta.env.BASE_URL}${locale === 'ru' ? 'ru/' : ''}${path}`;
